### ISSUE TITLE
v2.6.0 hangs initiating

### ISSUE THREAD

**Issue by bege10** [MuntashirAkon/AppManager#454]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
After update to v2.6.0 App Manager hangs at start screen initiating. Progress circle continuously turns

**To Reproduce**
Steps to reproduce the behaviour:
1. Start
2. See error

**Expected behavior**
Show apps list

**Screenshots**

**Crash logs**
I will add later if necessary.

**Device info**
 - Device: Fairphone 3
 - OS Version: /e/OS, Android 10
 - App Manager Version: v2.6.0
 - Mode: root Magisk

**Additional context**

**Comment by bege10** [comment]
> 
> 
> Did you restart your phone after updating App Manager?

Yes, doesn't help
Here's a log:
[logreader_2021-05-25_19-34.log](https://github.com/MuntashirAkon/AppManager/files/6542685/logreader_2021-05-25_19-34.log)

**Comment by MuntashirAkon** [comment]
> Here's a log:
> [logreader_2021-05-25_19-34.log](https://github.com/MuntashirAkon/AppManager/files/6542685/logreader_2021-05-25_19-34.log)

Doesn't seem to contain anything other than a few system calls. Perhaps you or the logging client you're using are applying filters which filtering out the important logs.

**Comment by bege10** [comment]
adb logcat doesn't show more.
This entry
`05-26 02:19:30.624 18641 18641 W su      : type=1400 audit(0.0:382): avc: denied { read } for name="bin" dev="dm-0" ino=17 scontext=u:r:magisk_client:s0:c52,c257,c512,c768 tcontext=u:object_r:vendor_file:s0 tclass=dir permissive=0 app=io.github.muntashirakon.AppManager`
which is also at the bottom of the linked log made me uninstall and reboot the device to be sure it is removed from Magisk's list of allowed apps. Then I installed AM again, granted root access and by now it works. I guess that something with granted root access was wrong although AM was in Magisk's list of apps with root access.
For now I close this issue. If it comes back I can reopen it.

**Comment by bege10** [comment]
New day, old issue. The issue and the entry in logcat are back. Revoking and after request granting root access in Magisk doesn't help. I must re-install App Manager.

**Comment by MuntashirAkon** [comment]
> New day, old issue. The issue and the entry in logcat are back. Revoking and after request granting root access in Magisk doesn't help. I must re-install App Manager.

This appears to be an issue with Magisk itself but this should've been fixed in Magisk v23.0.

If this happens again, do the following to test if it's the Magisk issue:
1. In your favourite terminal app, run the following:
    ```
    su -c "ls /"
    ```
    And see if it lists the contents of the root directory.
2. Do the same as above but in the ADB shell.
3. If one or both worked, run `su -c "setenforce 0"` in the working terminal to set SELinux to permissive temporarily, and then open App Manager to see what happens.

This could also happen if your system is soft-rebooted. Soft-reboot issue is present in Lineage OS 17.1 to 18.1 (I think). Since /e/ OS is basically Lineage OS, the issue should be present there too. If this is the issue, then simply restarting your device should fix it.

**Comment by bege10** [comment]
----------------------------------------


>> New day, old issue. The issue and the entry in logcat are back. Revoking and after request granting root access in Magisk doesn't help. I must re-install App Manager.
>> 
> This appears to be an issue with Magisk itself but this should've been fixed in Magisk v23.0.
> 

I have 23001. This happens only with App Manager 2.6.0, with no other app and not even with App Manager 2.5.17.
> 
> 
> If this happens again, do the following to test if it's the Magisk issue:
> 
1. > In your favourite terminal app, run the following:
2. > su -c "ls /"
3. > And see if it lists the contents of the root directory.
4. > Do the same as above but in the ADB shell.

This test woks ok.
> 
1. > If one or both worked, run *su -c "setenforce 0"* in the working terminal to set SELinux to permissive temporarily, and then open App Manager to see what happens.

Still the same. (I reassured that SELinux was really deactivated.)
> 
> 
> This could also happen if your system is soft-rebooted. Soft-reboot issue is present in Lineage OS 17.1 to 18.1 (I think). Since /e/ OS is basically Lineage OS, the issue should be present there too. If this is the issue, then simply restarting your device should fix it.

I did this before and now again. It doesn't help.

**Comment by MuntashirAkon** [comment]
Run the following command in any terminal: (assuming you're running v2.6.0 release)
```
CLASSPATH=/data/local/tmp/main.jar /system/bin/app_process  /system/bin io.github.muntashirakon.AppManager.server.IPCMain io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.ipc.AMService io.github.muntashirakon.AppManager.ipc.IPCServer
```

**Comment by bege10** [comment]
> > New day, old issue. The issue and the entry in logcat are back. Revoking and after request granting root access in Magisk doesn't help. I must re-install App Manager.
> 
> This appears to be an issue with Magisk itself but this should've been fixed in Magisk v23.0.
> 
I have 23001. This happens only with App Manager 2.6.0, with no other app and not even with App Manager 2.5.17.
> If this happens again, do the following to test if it's the Magisk issue:
> 
>     1. In your favourite terminal app, run the following:
>        ```
>        su -c "ls /"
>        ```  
>        And see if it lists the contents of the root directory.
> 
>     2. Do the same as above but in the ADB shell.

This test woks ok.
>     3. If one or both worked, run `su -c "setenforce 0"` in the working terminal to set SELinux to permissive temporarily, and then open App Manager to see what happens.
> 
Still the same. (I reassured that SELinux was really deactivated.)
> This could also happen if your system is soft-rebooted. Soft-reboot issue is present in Lineage OS 17.1 to 18.1 (I think). Since /e/ OS is basically Lineage OS, the issue should be present there too. If this is the issue, then simply restarting your device should fix it.

I did this before and now again. It doesn't help.

**Comment by bege10** [comment]
> Run the following command in any terminal: (assuming you're running v2.6.0 release)
> 
> ```
> CLASSPATH=/data/local/tmp/main.jar /system/bin/app_process  /system/bin io.github.muntashirakon.AppManager.server.IPCMain io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.ipc.AMService io.github.muntashirakon.AppManager.ipc.IPCServer
> ```

With or without su?

**Comment by MuntashirAkon** [comment]
> With or without su?

Never mind. This won't work.

Another reason could be the namespace issue. Check in the Magisk settings if the **Mount Namespace Mode** is set to **Global Namespace**. If not, set it to **Global Namespace**.

**Comment by bege10** [comment]
> Another reason could be the namespace issue. Check in the Magisk settings if the **Mount Namespace Mode** is set to **Global Namespace**. If not, set it to **Global Namespace**.

It doesn't make a change before and after rebooting the phone.

(I must close for now. Thank you anyway.)

**Comment by MuntashirAkon** [comment]
> It doesn't make a change before and after rebooting the phone.

I need to know where exactly does it fail. Next time install a debug build and take full logs using logcat.

**Comment by bege10** [comment]
> I need to know where exactly does it fail. Next time install a debug build and take full logs using logcat.
Where do I find a debug build?

**Comment by MuntashirAkon** [comment]
> Where do I find a debug build?

See [docs](https://muntashirakon.github.io/AppManager/en/#x1-60001.3.1).

**Comment by bege10** [comment]
> I need to know where exactly does it fail. Next time install a debug build and take full logs using logcat.

v2.6.1 DEBUG works correct.

I wrote that 2.5.17 did not have that issue. That was wrong. It did not hang at starting the app but it showed the same entry in logcat when I opened the App Ops and no ops where displayed. #453

**Comment by MuntashirAkon** [comment]
Collect logs using [v2.6.x debug build](https://github.com/MuntashirAkon/AppManager/actions/runs/1133078108) rather than the stable release. You can install it side by side with the stable release since they have a different package name.

**Comment by anedroid** [comment]
This problem still appears sometimes on AppManager version 2.6.3 and requires system reboot. Here's my logcat filtered with "AppManager":

```
09-21 11:13:07.637  5337 11621 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.github.muntashirakon.AppManager/.main.MainActivity bnds=[20,931][156,1148]} from uid 10141
09-21 11:13:07.684  5337  5367 I ActivityManager: Start proc 21244:io.github.muntashirakon.AppManager/u0a352 for pre-top-activity {io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.main.MainActivity}
09-21 11:13:07.991  5337 11621 I ActivityTaskManager: START u0 {cmp=io.github.muntashirakon.AppManager/.crypto.AuthenticationActivity} from uid 10352
09-21 11:13:08.216  5337  5865 E ActivityManager: Sending non-protected broadcast io.github.muntashirakon.AppManager.action.SERVER_CONNECTED from system uid 0 pkg null
09-21 11:13:08.216  5337  5865 E ActivityManager: java.lang.Throwable
09-21 11:13:08.216  5337  5865 E ActivityManager:       at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:15914)
09-21 11:13:08.216  5337  5865 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:16585)
09-21 11:13:08.216  5337  5865 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:15927)
09-21 11:13:08.216  5337  5865 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:16741)
09-21 11:13:08.216  5337  5865 E ActivityManager:       at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2283)
09-21 11:13:08.216  5337  5865 E ActivityManager:       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2875)
09-21 11:13:08.216  5337  5865 E ActivityManager:       at android.os.Binder.execTransactInternal(Binder.java:1154)
09-21 11:13:08.216  5337  5865 E ActivityManager:       at android.os.Binder.execTransact(Binder.java:1123)
09-21 11:13:08.321  5337  5365 I ActivityTaskManager: Displayed io.github.muntashirakon.AppManager/.crypto.AuthenticationActivity: +675ms
09-21 11:13:08.738 21298 21298 D AndroidRuntime: Calling main entry io.github.muntashirakon.AppManager.server.IPCMain
```

- Android 11: LineageOS 18.1 (update 6.09.2021) with microG
- Moto g7 Power (ocean)
- Magisk 23.0
